packages:
  - packages/**
catalog:
  eslint: ^9.22.0
  prettier: ^3.5.3
  typescript: ^5.8.2
  vite: ^6.2.1
  vitepress: ^1.6.3
  vitest: ^3.0.8
  vue: ^3.5.13
  lint-staged: ^15.4.3
  "axios": "^1.8.4"
  "rollup": "^4.37.0"
  "rollup-plugin-dts": "^6.2.1"
  "rollup-plugin-esbuild": "^6.2.1"
  "rollup-plugin-pure": "^0.3.0"
  "@rollup/plugin-json": "^6.1.0"
  "vue-tsc": "^2.2.8"
  "tsx": "^4.19.3"
  "@types/node": "^22.13.12"
